name: Deploy

on:
  push:
    branches:
      - hotfix/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run security scanner
        run: security_scan --strict

  deploy:
    needs: [build, security-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: ./deploy.sh
